# base image source https://github.com/rhdt/EL-Dockerfiles/blob/master/base/python3/Dockerfile
FROM quay.io/openshiftio/rhel-base-python3:latest

ENV APP_DIR=/github_refresh

RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}

COPY . ${APP_DIR}
RUN pip3 install --upgrade pip>=10.0.0 && pip3 install -r requirements.txt

CMD ["python3", "./github_refresh.py"]
