apiVersion: v1
kind: Template
labels:
  template: f8a-github-refresh-cronjob
metadata:
  name: f8a-github-refresh-cronjob
  annotations:
    description: f8a-github-refresh-cronjob
objects:
- apiVersion:  batch/v1beta1
  kind: CronJob
  metadata:
    name: f8a-github-refresh-cronjob
    annotations:
      description: f8a-github-refresh-cronjob
  spec:
    successfulJobsHistoryLimit: 2
    failedJobsHistoryLimit: 2
    concurrencyPolicy: "Forbid"
    schedule: "${CRON_SCHEDULE}"
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: f8a-github-refresh-cronjob
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              env:
                - name: DEPLOYMENT_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: deployment-prefix
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: aws-default-region
                - name: AWS_S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-secret-access-key
                - name: AWS_S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-access-key-id
                - name: REPORT_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: bucket
                - name: WORKER_ADMINISTRATION_REGION
                  value: "ingestion"
                - name: DRY_RUN
                  value: "${DRY_RUN}"
                - name: REPORT_TIME_DELTA
                  value: "0"
                - name: PGBOUNCER_SERVICE_HOST
                  value: bayesian-pgbouncer
                - name: PGBOUNCER_SERVICE_PORT
                  value: "5432"
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: coreapi-postgres
                      key: database
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coreapi-postgres
                      key: password
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: coreapi-postgres
                      key: username
                - name: AWS_SQS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: sqs-access-key-id
                - name: AWS_SQS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: sqs-secret-access-key
                - name: REFRESH_INTERVAL
                  value: 0
              resources:
                requests:
                  memory: ${MEMORY_REQUEST}
                  cpu: ${CPU_REQUEST}
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
parameters:
- description: Docker registry
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-github-refresh-cronjob"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Dry run
  displayName: Dry run
  required: true
  name: DRY_RUN
  value: "false"

- description: Schedule
  displayName: Schedule
  required: true
  name: CRON_SCHEDULE
  value: "0 3 * * *"

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "250m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "500m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "256Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "1536Mi"
